# Generated by Django 4.2.1 on 2023-05-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cartdetail",
            name="sub_price",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
