# Generated by Django 4.2.1 on 2023-05-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
